#!/usr/bin/env python3
"""
rom_loader.py
─────────────────────────────────────────────────────────────
Converts a compiled.RAM text file into a Verilog.mem hex
file suitable for loading into the ROM simulation via
$readmemh..RAM file format:
  - One instruction per line
  - Each line is an 8-bit binary string e.g. "10110011"
  - No comments, labels, or metadata

ROM spec:
  - 8-bit (1 byte) data width
  - 64 addresses (0x00 – 0x3F)

Usage:
  python rom_loader.py <input.RAM> [output.mem]

If no output filename is given, it defaults to "program.mem".
─────────────────────────────────────────────────────────────
"""

import sys
import os

# ── Constants ────────────────────────────────────────────────
ROM_DEPTH     = 64    # Number of addressable ROM locations (6-bit: 2^6)
ROM_DATA_BITS = 8     # Bits per ROM word
ROM_PAD_BYTE  = 0xC9  # Padding for unused ROM locations (11001001) - NOP


def load_ram_file(filepath: str) -> list[int]:
    """
    Read a text-based.RAM file where each line is an 8-bit
    binary string (e.g. "10110011"), and return a list of
    integer byte values.
    """
    if not os.path.isfile(filepath):
        print(f"[ERROR] File not found: {filepath}")
        sys.exit(1)

    instructions = []

    with open(filepath, "r") as f:
        for line_num, line in enumerate(f, start=1):
            stripped = line.strip()

            # Skip any blank lines defensively
            if not stripped:
                continue

            # Validate that the line is exactly 8 binary characters
            if len(stripped) != ROM_DATA_BITS or not all(c in "01" for c in stripped):
                print(
                    f"[ERROR] Line {line_num}: Expected an {ROM_DATA_BITS}-bit binary "
                    f"string, got: '{stripped}'"
                )
                sys.exit(1)

            # Convert binary string to integer
            instructions.append(int(stripped, 2))

    print(f"[INFO] Parsed {len(instructions)} instruction(s) from '{filepath}'.")
    return instructions


def validate_size(instructions: list[int]) -> list[int]:
    """Warn and truncate if the program exceeds ROM capacity."""
    if len(instructions) > ROM_DEPTH:
        print(
            f"[WARNING] Program has {len(instructions)} instructions, but ROM only "
            f"has {ROM_DEPTH} locations. Truncating at address 0x{ROM_DEPTH - 1:02X}."
        )
        return instructions[:ROM_DEPTH]
    return instructions


def generate_mem_file(instructions: list[int], output_path: str):
    """
    Write a Verilog $readmemh-compatible.mem file.

    Format:
      - One hex byte per line (no '0x' prefix)
      - Address comments every 16 bytes for readability
      - Remaining ROM locations padded with ROM_PAD_BYTE
    """
    lines = []
    lines.append("// ================================================")
    lines.append("// ROM Program Image — generated by rom_loader.py")
    lines.append(f"// ROM depth   : {ROM_DEPTH} x {ROM_DATA_BITS}-bit words")
    lines.append(f"// ROM padding : 0x{ROM_PAD_BYTE:02X} ({ROM_PAD_BYTE:08b}) for unused locations")
    lines.append("// ================================================")
    lines.append("")

    for addr in range(ROM_DEPTH):
        # Add an address marker comment every 16 locations
        if addr % 16 == 0:
            lines.append(f"// Address 0x{addr:02X} – 0x{min(addr + 15, ROM_DEPTH - 1):02X}")

        if addr < len(instructions):
            lines.append(f"{instructions[addr]:02X}")
        else:
            lines.append(f"{ROM_PAD_BYTE:02X}")

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[INFO] Written {ROM_DEPTH} ROM entries to '{output_path}'.")
    print(f"[INFO] Program occupies addresses 0x00 – 0x{len(instructions) - 1:02X}.")
    print(
        f"[INFO] Remaining {ROM_DEPTH - len(instructions)} location(s) "
        f"padded with 0x{ROM_PAD_BYTE:02X} ({ROM_PAD_BYTE:08b})."
    )


def main():
    # ── Argument Parsing ──────────────────────────────────────
    if len(sys.argv) < 2:
        print("Usage: python rom_loader.py <input.RAM> [output.mem]")
        sys.exit(1)

    input_file  = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) >= 3 else "program.mem"

    if not input_file.lower().endswith(".ram"):
        print(f"[WARNING] Expected a.RAM file, got: '{input_file}'")

    # ── Pipeline ──────────────────────────────────────────────
    instructions = load_ram_file(input_file)
    instructions = validate_size(instructions)
    generate_mem_file(instructions, output_file)

    print("[DONE] You can now simulate with:")
    print(f"         ROM_INIT_FILE = \"{output_file}\"")


if __name__ == "__main__":
    main()